spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: root
    hikari:
      schema: airport

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
