version: '3'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: airport_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SCHEMA=airport
      - USERNAME=postgres
      - PASSWORD=root
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root